#!/usr/bin/env bash

# Author: Dmitri Popov, dmpop@linux.com
# License: GPLv3 https://www.gnu.org/licenses/gpl-3.0.txt

f=$(basename -- "$@")
fn="${f%.*}"
fe=="${f##*.}"
dcraw -c "$@" | cjpeg -quality 100 -optimize -progressive > "$fn".jpg
exiftool -overwrite_original -tagsfromfile "$@" "$fn".jpg
notify-send "Action completed" -i info
