#!/usr/bin/env bash

# Author: Dmitri Popov, dmpop@cameracode.coffee
# License: GPLv3 https://www.gnu.org/licenses/gpl-3.0.txt

if [ ! -x "$(command -v convert)" ]; then
    notify-send "Install ImageMagick." -i info
    exit 1
fi

size=$(kdialog --inputbox 'Size in px:' --title 'Resize')
quality=$(kdialog --inputbox 'Quality in %:' --title 'Quality')
convert "$@" -resize "$size>" -quality "$quality%" "$@"
notify-send "All done!" -i info
