#!/usr/bin/env bash

# Author: Dmitri Popov, dmpop@cameracode.coffee
# License: GPLv3 https://www.gnu.org/licenses/gpl-3.0.txt

d=$(pwd)
python3 -m http.server 8000 -d "$d" & disown
pid=$(echo $!)
sleep 30
kill -9 $pid