#!/usr/bin/env bash

# Author: Dmitri Popov, dmpop@linux.com
# License: GPLv3 https://www.gnu.org/licenses/gpl-3.0.txt

if [ ! -x "$(command -v exiftool)" ]; then
    notify-send "Install ExifTool" -i info
    exit 1
fi

c="$(exiftool -s3 -ShutterCount "$@")"
if [[ $c -gt 0 ]]; then
    notify-send "Shutter count: $c" -i info
else
    c="$(exiftool -s3 -ImageCount "$@")"
    if [[ $c -gt 0 ]]; then
        notify-send "Image count: $c" -i info
    else
        c="$(exiftool -s3 -ImageNumber "$@")"
        if [[ $c -gt 0 ]]; then
            notify-send "Image number: $c" -i info
        else
            notify-send "Unknown" -i info
        fi
    fi
fi
