#!/usr/bin/env bash

# Author: Dmitri Popov, dmpop@linux.com
# License: GPLv3 https://www.gnu.org/licenses/gpl-3.0.txt

exiftool '-filename<CreateDate' -d %Y%m%d-%H%M%S%%-c.%%ue "$@"
notify-send "Action completed" -i info
