#!/usr/bin/env bash

# Author: Dmitri Popov, dmpop@linux.com
# License: GPLv3 https://www.gnu.org/licenses/gpl-3.0.txt

f=$(echo $NEMO_SCRIPT_SELECTED_URIS | sed 's@file://@@g')

if [ ! -x "$(command -v convert)" ]; then
    notify-send "Install ImageMagick." -i info
    exit 1
fi

size=$(zenity --entry --text 'Size in px' --title 'Resize')
quality=$(zenity --entry --text 'Quality in %' --title 'Quality')
mogrify -resize "$size>" -quality "$quality%" "$f"
notify-send "Action completed" -i info
