#!/usr/bin/env bash

# Author: Dmitri Popov, dmpop@tokyoma.de
# License: GPLv3 https://www.gnu.org/licenses/gpl-3.0.txt

if [ ! -x "$(command -v convert)" ]; then
    notify-send "Install ImageMagick." -i info
    exit 1
fi

size=$(zenity --entry --text 'Size in px' --title 'Resize')
quality=$(zenity --entry --text 'Quality in %' --title 'Quality')
mogrify -resize "$size>" -quality "$quality%" "$@"
notify-send "All done!" -i info
