#!/usr/bin/env bash

# Author: Dmitri Popov, dmpop@tokyoma.de
# License: GPLv3 https://www.gnu.org/licenses/gpl-3.0.txt

f=$(echo $NEMO_SCRIPT_SELECTED_URIS | sed 's@file://@@g')

d=$(mktemp -d)
cp "$f" "$d"
python3 -m http.server 8000 -d "$d"