#!/usr/bin/env bash

# Author: Dmitri Popov, dmpop@tokyoma.de
# License: GPLv3 https://www.gnu.org/licenses/gpl-3.0.txt

f="$@"

lat=$(exiftool -n -p '$GPSlatitude' "$f")
lon=$(exiftool -n -p '$GPSlongitude' "$f")
osm="http://www.openstreetmap.org/?mlat=$lat&mlon=$lon&zoom=18"
xdg-open $osm
