#!/usr/bin/env bash

# Author: Dmitri Popov, dmpop@linux.com
# License: GPLv3 https://www.gnu.org/licenses/gpl-3.0.txt

CONFIG="$HOME/.ai"

check1=$(wget -q --spider http://photon.komoot.de/)
if [ ! -z $check1]; then
    yad --skip-taskbar --undecorated --borders=75 \
	--timeout=3 --no-buttons --center \
	--text="<big>Photon is not reachable. Check your Internet connection.</big>"
    exit 1
fi

if [ ! -f "$CONFIG" ]; then
    copyright=$(yad --center --width=500 --form --field="Copyright notice:" | cut -d"|" -f1)
    echo 'copyright="'$copyright'"' >> "$CONFIG"
    ext=$(yad --center --width=500 --form --field="Dark Sky API key:" | cut -d"|" -f1)
    echo 'ext="'$ext'"' >> "$CONFIG"
    echo 'json="$HOME/weather.json"' >> "$CONFIG"
    echo "Provide Dark Sky API key and press [ENTER]"
    api_key=$(yad --center --width=500 --form --field="Dark Sky API key:" | cut -d"|" -f1)
    echo 'api_key="'$api_key'"' >> "$CONFIG"
fi
source "$CONFIG"

f=$(yad --center --text-align=center --title="Add Photos" --button=gtk-cancel:0 \
	--button="Continue":0 --borders=15 --width=250 --height=150 \
	--text='<big>\nDrop JPEG files here.\nPress the <b>Continue</b> button.</big>' \
	--dnd | sed 's/^.......//')
city=$(yad --center --width=400 --form --field="Enter city:" | cut -d"|" -f1)

if [ ! -z "$f" ]; then

    lat=$(curl "photon.komoot.de/api/?q=$city" | jq '.features | .[0] | .geometry | .coordinates | .[1]')
    if (( $(echo "$lat > 0" |bc -l) )); then
        latref="N"
    else
        latref="S"
    fi

    lon=$(curl "photon.komoot.de/api/?q=$city" | jq '.features | .[0] | .geometry | .coordinates | .[0]')
    if (( $(echo "$lon > 0" |bc -l) )); then
        lonref="E"
    else
        lonref="W"
    fi

    while IFS= read -r photo
    do
        exiftool -overwrite_original -copyright="$copyright" -GPSLatitude="$lat" -GPSLatitudeRef="$latref" -GPSLongitude="$lon" -GPSLongitudeRef="$lonref" "$photo"
    done < <(printf '%s\n' "$f")
    check2=$(wget -q --spider https://api.darksky.net/)
    if [ -z $check2 ]; then
        while IFS= read -r photo
        do
            t=$(exiftool -d %Y-%m-%d -DateTimeOriginal $photo | cut -d":" -f2 | tr -d " " | xargs -I dt date --date=dt +"%s")
            camera=$(exiftool -Model $photo | cut -d":" -f2 | tr -d " ")
            lens=$(exiftool -LensID $photo | cut -d":" -f2)
            curl "https://api.darksky.net/forecast/"$api_key"/"$lat","$lon","$t"?units=si&exclude=currently,hourly,flags" > $json
            w_sum=$(jq '.daily | .data | .[0] | .summary' $json | tr -d '"')
            w_temp=$(jq '.daily | .data | .[0] | .temperatureHigh' $json | tr -d '"')
            exiftool -overwrite_original -comment="$camera, $lens, $w_temp°C, $w_sum" "$photo"
        done < <(printf '%s\n' "$f")
    fi
    
    rm $json
    yad --skip-taskbar --button=gtk-close:0 --center \
	--text="<big>All done. Bye!</big>"
else
    yad --skip-taskbar --undecorated --borders=75 \
	--timeout=3 --no-buttons --center \
	--text="<big>Nothing to do. Bye!</big>"
    exit 1
fi
