#!/bin/bash

f=$(basename -- "$@")
fn="${f%.*}"
fe=="${f##*.}"
dcraw -c "$@" | cjpeg -quality 100 -optimize -progressive > "$fn".jpg
exiftool -overwrite_original -tagsfromfile "$@" "$fn".jpg
notify-send "Action completed" -i info
