#!/bin/bash

if [ ! -x "$(command -v convert)" ]; then
    notify-send "Install ImageMagick." -i info
    exit 1
fi

dialog=$(yad --title "Bash Resize" --form --field="Dimension in px" --field="Quality in %")

size=$(echo $dialog | awk 'BEGIN {FS="|" } { print $1 }')
quality=$(echo $dialog | awk 'BEGIN {FS="|" } { print $2 }')
size+=">"
convert "$@" -resize "$size>" -quality "$quality%" "$@"
notify-send "Action completed" -i info 
