#!/usr/bin/env bash

# Author: Dmitri Popov, dmpop@linux.com
# License: GPLv3 https://www.gnu.org/licenses/gpl-3.0.txt

if [ -x "$(command -v exiftool)" ] ; then
    lat=`exiftool -n -p '$GPSlatitude' $1`
    lon=`exiftool -n -p '$GPSlongitude' $1`
    osm="http://www.openstreetmap.org/?mlat=$lat&mlon=$lon&zoom=18"
    xdg-open $osm
fi
