#!/usr/bin/env bash

# Author: Dmitri Popov, dmpop@linux.com
# License: GPLv3 https://www.gnu.org/licenses/gpl-3.0.txt

if [ -z "$(command -v notify-send)" ] || [ -z "$(command -v exiftool)" ]; then
  echo "Make sure that exiftool and notify-send are installed."
  exit 1
fi

if [ -z "$@" ]; then
    echo "Please specify the path to the file."
    exit 1
fi

shuttercountgrep=$(exiftool "$@" | grep "Shutter Count" | cut -d":" -f2 | tr -d " ")
if [ ! -z "$shuttercountgrep" ]; then
    notify-send "Shutter Count: $shuttercountgrep"
    exit 1
fi

shuttecount=$(exiftool -ShutterCount "$@" | cut -d":" -f2 | tr -d " ")
if [ ! -z "$shuttercount" ]; then
    notify-send "Shutter count: $shuttercount"
    exit 1
fi

imagenumber=$(exiftool -ImageNumber "$@" | cut -d":" -f2 | tr -d " ")
if [ ! -z "$imagenumber" ]; then
    notify-send "Image number: $imagenumber"
    exit 1
fi

imagecount=$(exiftool -ImageCount "$@" | cut -d":" -f2 | tr -d " ")
if [ ! -z "$imagecount" ]; then
    notify-send "Image count: $imagecount"
    exit 1
fi

notify-send "No shutter count data found."
