#!/usr/bin/env bash

# Author: Dmitri Popov, dmpop@linux.com
# License: GPLv3 https://www.gnu.org/licenses/gpl-3.0.txt

f=`echo $NAUTILUS_SCRIPT_SELECTED_URIS | sed 's@file://@@g'`

CONFIG="$HOME/ai.cfg"

if [ ! -f "$CONFIG" ]; then
    copyright=$(kdialog --inputbox 'Copyright notice:' --title 'Copyright')
    echo 'copyright="'$copyright'"' >> "$CONFIG"
    echo 'json="$HOME/weather.json"' >> "$CONFIG"
    api_key=$(kdialog --inputbox 'Dark Sky API key:' --title 'Dark Sky API Key')
    echo 'api_key="'$api_key'"' >> "$CONFIG"
fi
source "$CONFIG"

check=$(wget -q --spider https://api.darksky.net/)
if [ -z $check ]; then
    lat=$(exiftool "$1" -gpslatitude -n | cut -d":" -f2 | tr -d " ")
    lon=$(exiftool "$1" -gpslongitude -n | cut -d":" -f2 | tr -d " ")
    if [ ! -z "$lat" ] && [ ! -z "$lon" ]; then
	t=$(exiftool -d %Y-%m-%d -DateTimeOriginal "$f" | cut -d":" -f2 | tr -d " " | xargs -I dt date --date=dt +"%s")
	camera=$(exiftool -Model "$f" | cut -d":" -f2 | tr -d " ")
	lens=$(exiftool -LensID "$f" | cut -d":" -f2)
	curl "https://api.darksky.net/forecast/"$api_key"/"$lat","$lon","$t"?units=si&exclude=currently,hourly,flags" > $json
	w_sum=$(jq '.daily | .data | .[0] | .summary' $json | tr -d '"')
	w_temp=$(jq '.daily | .data | .[0] | .temperatureHigh' $json | tr -d '"')
	exiftool -overwrite_original -copyright="$copyright" -comment="$camera $lens $w_temp°C $w_sum" "$f"
    else
	notify-send "$f is not geotagged"
    fi
    if [ -d "$json" ]; then
	rm "$json"
    fi
    notify-send "All done. Bye!"
else
    notify-send "Dark Sky API is not reachable."
    exit 1
fi
