#!/usr/bin/env bash

# Author: Dmitri Popov, dmpop@linux.com
# License: GPLv3 https://www.gnu.org/licenses/gpl-3.0.txt

f=`echo $NAUTILUS_SCRIPT_SELECTED_URIS | sed 's@file://@@g'`
fn="${f%.*}"
fe=="${f##*.}"
dcraw -c "$f" | cjpeg -quality 100 -optimize -progressive > "$fn".jpg
exiftool -overwrite_original -tagsfromfile "$f" "$fn".jpg
notify-send "Action completed" -i info
